### ISSUE TITLE
Problem installing SBH adapter using pip 20.2.2

### ISSUE THREAD

**Issue by georgebzheng** [SD2E/synbiohub_adapter#124]
Using pip 20.2.2 and 2020-resolver, we encountered the following error during the build for fcs-etl-application:
```
Step 6/8 : RUN pip3 install git+https://github.com/SD2E/synbiohub_adapter.git --use-feature=2020-resolver
 ---> Running in afd37ddbf4fa
Collecting git+https://github.com/SD2E/synbiohub_adapter.git
  Cloning https://github.com/SD2E/synbiohub_adapter.git to /tmp/pip-req-build-zj1e4bwn
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zj1e4bwn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zj1e4bwn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-li3u4jy0
         cwd: /tmp/pip-req-build-zj1e4bwn/
    Complete output (17 lines):
    /usr/local/lib/python3.6/dist-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
      warnings.warn("Setuptools is replacing distutils.")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zj1e4bwn/setup.py", line 22, in <module>
        "Programming Language :: Python :: 3 :: Only"
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 665, in parse_config_files
        self._parse_config_files(filenames=filenames)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 572, in _parse_config_files
        filenames = self.find_config_files()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/dist.py", line 353, in find_config_files
        sys_dir = os.path.dirname(sys.modules['distutils'].__file__)
    KeyError: 'distutils'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip3 install git+https://github.com/SD2E/synbiohub_adapter.git --use-feature=2020-resolver' returned a non-zero code: 1
Error building sd2e/fcs-etl:0.4.4
```

**Comment by mwes** [comment]
FYI this is related to testing an upcoming change to pip and dependency resolution: https://pip.pypa.io/en/stable/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020

This change is targeted for October, 2020, so we are evaluating this resolver under the current SD2 packages to ensure we can maintain our builds.

**Comment by mwes** [comment]
A follow up: This error is related to the latest version of setuptools (50.0.0): https://github.com/pypa/setuptools/issues/2355

Using setuptools 49.6.0 I confirmed this module resolves fine with the 2020-resolver.
