### ISSUE TITLE
IndentationError on import

### ISSUE THREAD

**Issue by tcmitchell** [SD2E/synbiohub_adapter#53]
As in #32 an indentation error prevents using the current synbiohub_adapter (at commit 23c7c55db45ec0a88644089c9cfcdd10bb17672d). It looks like there is mixed indentation in the file synbiohub_adapter/SynBioHubUtil.py which may be a root cause. As indicated in #32, space is the canonical indentation, and tabs should not be used.

This issue prevents the use of synbiohub_adapter altogether because there are no releases/tags to revert back to.

This issue can be replicated via unit tests and via the python interpreter.

To replicate via the unit tests:

```
$ python3 -m unittest discover tests
E
======================================================================
ERROR: tests.test_fallback_cache (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_fallback_cache
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/usr/local/lib/python3.6/dist-packages/tests/test_fallback_cache.py", line 1, in <module>
    from synbiohub_adapter.cache_query import wrap_query_fn, db_dir
  File "/usr/local/lib/python3.6/dist-packages/synbiohub_adapter/__init__.py", line 1, in <module>
    from synbiohub_adapter.SynBioHubUtil import (
  File "/usr/local/lib/python3.6/dist-packages/synbiohub_adapter/SynBioHubUtil.py", line 190
    def construct_type_pattern(self, types, all_types=True, entity_label='entity', type_label='type'):
                                                                                                     ^
IndentationError: unindent does not match any outer indentation level


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

To replicate via the interpreter:

```
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import synbiohub_adapter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/synbiohub_adapter/__init__.py", line 1, in <module>
    from synbiohub_adapter.SynBioHubUtil import (
  File "/usr/local/lib/python3.6/dist-packages/synbiohub_adapter/SynBioHubUtil.py", line 190
    def construct_type_pattern(self, types, all_types=True, entity_label='entity', type_label='type'):
                                                                                                     ^
IndentationError: unindent does not match any outer indentation level
>>> 
```

**Comment by bbartley** [comment]
Commits adff856a29d9861e4cdeb571caac7729cc57744a and af195035fbe9a2243174f12a1f2c537c2c350eed should fix the indentation problem, but don't immediately solve the failing tests.  Nic's subsequent commits will update the tests to support secure SPARQL queries
